backend/WebUI/api_webui.go
frontend/yarn.lock
go.sum

Refer to GitHub Issue [#267](https://github.com/free5gc/free5gc/issues/267)
- To replace all periods(.) in DNN to underscores(_) before subscription data be sent to the backend.
- To replace all underscores(_) in DNN to periods(.) after subscription data be received from the backend.
After data transmission succeeds, let's check out the sm_data in MongoDB:
we can see that the key of DNN which contains periods(.), was replaced successfully.

fix: PDU session cannot be established if DNN contains a period(.)

---

frontend/src/pages/Subscribers/SubscriberOverview.js
frontend/src/pages/Subscribers/components/SubscriberModal.js

- support to add multi subscribers at once
- IMSI number is incremented by one for each of the UEs

support to add multi subscribers at once

---

backend/WebUI/api_webui.go
backend/WebUI/model_tenant_data.go
backend/WebUI/model_user_data.go
backend/WebUI/routers.go
frontend/src/components/SideBar/Nav.js
frontend/src/models/Tenant.js
frontend/src/models/User.js
frontend/src/pages/Main/index.js
frontend/src/pages/Subscribers/SubscriberOverview.js
frontend/src/pages/Tenants/TenantOverview.js
frontend/src/pages/Tenants/components/TenantModal.js
frontend/src/pages/Tenants/index.js
frontend/src/pages/Users/UserOverview.js
frontend/src/pages/Users/components/UserModal.js
frontend/src/pages/Users/index.js
frontend/src/redux/actions/tenantActions.js
frontend/src/redux/actions/userActions.js
frontend/src/redux/reducers/index.js
frontend/src/redux/reducers/tenant.js
frontend/src/redux/reducers/user.js
frontend/src/util/ApiHelper.js
frontend/src/util/AuthHelper.js
frontend/src/util/LocalStorageHelper.js
frontend/src/util/UEInfoApiHelper.js
go.mod
go.sum

This PR add Tenant and User for each Subscriber information.  With this change, we can start supporting multi tenant architecture in webconsole.

Multi tenant support in webconsole

---

readme.md

Hi,
The default credentials are referenced in the wiki here https://github.com/free5gc/free5gc/wiki/New-Subscriber-via-webconsole but I find it appropriate to have them also included in the WebUI readme file.
Cheers,

Include default credentials in WebUI readme

---

backend/WebUI/api_webui.go
backend/webui_service/webui_init.go
frontend/package.json
frontend/src/components/SideBar/Nav.js
frontend/src/metadata/index.js
frontend/src/pages/Auth/Login.js
frontend/src/pages/Users/components/UserModal.js
frontend/src/util/AuthHelper.js
frontend/yarn.lock

This PR resolve the **CSRF** vulnerability by **JWT** (Json Web Token). 
Now, if clients want to request the RESTful API, they could not use **"admin"** as token.
The only way to get the JWT token is to login through Webconsole's **Login page**.

fix: CSRF vulnerability

---

backend/WebUI/api_webui.go
frontend/package.json
frontend/yarn.lock

This PR is to fix [github issue #435](https://github.com/free5gc/free5gc/issues/435)

Sd mismatch issue, make Sd value to lower case in dbOperation()

---

backend/webui_service/webui_init.go

The binding IP address and port for WebUI can be set as follows.
According to `config.go`, `scheme` parameter in `webuicfg.yaml` is a required attribute, so this parameter is not used in `webui_init.go`, but set it to `http` for the time being.
For example of `webuicfg.yaml`
```
@@ -3,6 +3,10 @@
description: WebUI initial local configuration
configuration:
+  webServer:
+    scheme: http
+    ipv4Address: 192.168.0.141
+    port: 5001
mongodb: # the mongodb connected by this webui
name: free5gc # name of the mongodb
url: mongodb://localhost:27017 # a valid URL of the mongodb
```
In this case, starting the WebUI will output the log as follows.
```
...
2023-08-12T19:50:01.692442110+09:00 [INFO][WEBUI][Init] Create tenant: admin
2023-08-12T19:50:01.693665041+09:00 [INFO][WEBUI][Init] Create …
```

Configurable binding IP address and port in webuicfg.yaml

---

backend/factory/config.go
backend/webui_context/context.go
backend/webui_context/nrf.go
backend/webui_service/webui_init.go
config/webuicfg.yaml

Rigth now webconsole get NFProfile from mongodb but it is better to query to NRF directory to reducue involvement of mongodb.

Query to NRF for NFProfile instead of getting from mongodb.

---

backend/factory/config.go
backend/webui_service/webui_init.go
config/webuicfg.yaml

Billing server (FTP server) should be able to be disabled if there's no CHF deployed.
- Add new config attribute `configuration.billingServer.enable`
- If `configuration.billingServer.enable` is `false`, no billing server will start.

Disable Billing Server If Needed

---

backend/factory/config.go

- BillingServer enable config set to `required`
- Remove default value to enable or not

Fix: billingServer config adjustment

---

.github/workflows/commit-msg-check.yml
.github/workflows/go.yml
.github/workflows/golangci-lint.yml
backend/billing/client.go
backend/billing/server.go
backend/factory/factory.go
backend/webui_service/webui_init.go
go.mod
go.sum

- Add Commit Message Check 
- https://github.com/webiny/action-conventional-commits
- https://www.conventionalcommits.org/en/v1.0.0/
- Bump Go version to 1.21
- Adjust CI action version to latest

chore: bump go version and CI adjustment

---

frontend/src/pages/Charging/ChargingList.tsx

The charging table page showed two errors:
1. The table did not have unique keys/ identifiers for every row due to wrapping each TableRow in a fragment (<>...</>), which doesn't pass the key prop down to the actual TableRow component.
2. The table header was not correctly using the `<h3>` tag, which cannot be a direct child of TableHead
I fixed these errors, sorry for the small PR.

fix: rendering errors (missing key and h3 child of TableHeader)

---

frontend/src/Dashboard.tsx
frontend/src/SimpleListMenu.tsx
frontend/src/pages/AnalysisList.tsx
frontend/src/pages/ChangePassword.tsx
frontend/src/pages/Charging/ChargingTable.tsx
frontend/src/pages/StatusList.tsx
frontend/src/pages/StatusRead.tsx
frontend/src/pages/SubscriberCreate.tsx
frontend/src/pages/SubscriberList.tsx
frontend/src/pages/SubscriberRead.tsx
frontend/src/pages/TenantCreate.tsx
frontend/src/pages/TenantList.tsx
frontend/src/pages/TenantUpdate.tsx
frontend/src/pages/UserCreate.tsx
frontend/src/pages/UserList.tsx
frontend/src/pages/UserUpdate.tsx

I have added a Refresh configuration option to the header of all pages in the webconsole.
The default is set to "manual", so no page auto-refresh.
Upon configuring a different value, the page is automatically refreshed in the configured interval (e.g. every 5s), and the data is reloaded (from the core or the database).
This centralizes the auto-refresh that was hardcoded in the charging page, and makes it configurable.
The values are set in the Dashboard, which is included by every page component, so that the option is available for all pages in the webconsole. If it is not needed, the user can simply leave it at "manual".
Let me know if you find this helpful, or if you find any bugs or improvements!

feat: add configurable page auto-refresh to all pages (in Dashboard)

---

.github/workflows/commit-msg-check.yml
Makefile
backend/WebUI/api_charging.go
backend/billing/server.go
backend/webui_context/context.go
backend/webui_context/nrf_management.go
backend/webui_service/webui_init.go
config/webuicfg.yaml

- Use HTTP server with gin router
- Add a waiting group to wait for all servers terminated 
- Send Dereg only when AF is registered 
- Fix the charging table sometimes a mismatch 
- Adjust Billing Server FTP server settings

perf: update Web App termination procedure

---

backend/webui_service/webui_init.go
frontend/src/App.tsx
frontend/src/Dashboard.tsx
frontend/src/LoginContext.tsx
frontend/src/ProtectedRoute.tsx
frontend/src/SimpleListMenu.tsx
frontend/src/axios.tsx
frontend/src/pages/Login.tsx
frontend/src/pages/Logout.tsx

I noticed that the webconsole does not retain login information when the page is refreshed.
Using local storage, I implemented this missing functionality.
I also configured the axios token so that it survives page refreshes.

feat: Implement page refresh

---

backend/WebUI/api_verify.go
backend/WebUI/api_verify_test.go
go.mod

- Fix VerifyStaticIp when multiple pools
- Refactor related code 
- Add testcases
- https://github.com/free5gc/free5gc/issues/588

fix: VerifyStaticIp when multiple pools

---

frontend/src/lib/dtos/subscription.ts

I've found a typo in: frontend/src/lib/dtos/subscription.ts, the word "configuration" was written as "confiuration"(several parts).

chore: fix typo "confiuration" to "configuration"

---

frontend/src/pages/ProfileList.tsx
frontend/src/pages/ProfileRead.tsx
frontend/src/pages/SubscriberList.tsx
frontend/src/pages/SubscriberRead.tsx

1. re-assign the edit to the top of view page(SubscriberRead and ProfileRead)
2. add an edit button on both list page(SubscriberList and ProfileList)

refactor & feat /edit button

---

frontend/src/pages/Component/FlowRule.tsx
frontend/src/pages/ProfileRead.tsx
frontend/src/pages/SubscriberRead.tsx

In the Profile and Subscriber pages, there is an issue where the QoS Flow and its Charging Characteristics are displayed incorrectly, with the fields appearing empty.
Now, it is fixed:

fix: empty qosflow field in both profile and subscriber page

---

frontend/src/pages/SubscriberCreate/SubscriberFormSessions.tsx

Instead of using `switch`, I update this section with `controller`. It provides a stronger status track function which makes the switch display correct.
UE side test is work well as before.

fix: use controller to track the switch status
